### ISSUE TITLE
nt8property depends on nt8images

### ISSUE THREAD

**Issue by tobybatch** [neontabs/nt8#4]
Trying to create a new proiperty if the images module is switched off throws an error on ```field_cottage_image_info is unknown.```

https://gist.github.com/tobybatch/fd550f2663a07408aad95abdbaac302f

We either need to listed on a node create event (used to hook_node_prepare I think) and inject the image fields, or just make nt8property depend on nt8images

**Comment by ob6160** [comment]
Removed nt8images in https://github.com/neontabs/nt8/commit/954ad20e7a3e3d6c75c6d52bdf306306ed8c4759
